name: Gradle Build Action

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: change plugin.yml version
        run: |
          before="${{ steps.release-drafter.outputs.tag_name }}"
          after="${before//v/}"
          sed -i -e "s/miencraft_plugin_version/$after/i" './build.gradle.kts'
          cat ./build.gradle.kts

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          release: true
          title: "${{github.ref.name}}"
          files: |
            build/build/*.jar
            build.yml

